apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: default
data:
  default.conf: |
    # ./docker/nginx/default.conf
    server {
     server_name ~.*;

     location / {
         root /app;

         try_files $uri /index.php$is_args$args;
     }

     location ~ ^/index\.php(/|$) {
         client_max_body_size 50m;

         fastcgi_pass server-cluster-ip-service:9000;
         fastcgi_buffers 16 16k;
         fastcgi_buffer_size 32k;
         include fastcgi_params;
         fastcgi_param SCRIPT_FILENAME /app/public/index.php;
     }

     error_log /dev/stderr debug;
     access_log /dev/stdout;
    }

