apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: rabbitmq
  ports:
    - name: api
      port: 5672
      targetPort: 5672
    - name: panel
      port: 15672
      targetPort: 15672
    - name: panel2
      port: 15671
      targetPort: 15671
