#!/bin/bash

echo 'start install'
kubectl apply \
    -f ./rabbitmq/ \
    -f ./message-dashboard/ \
    -f ./message-service/ \
    -f ./monitoring/ \
    -f ./trigger-service/ \
    -f ./shared/
minikube addons enable ingress
echo 'end install'
