apiVersion: v1
kind: Service
metadata:
  name: trigger-service-mysql-cluster-ip
spec:
  type: ClusterIP
  selector:
    component: trigger-service-mysql
  ports:
    - port: 3306
      targetPort: 3306
