apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource-influxdb-config
  namespace: default
data:
  datasource.yml: |
    apiVersion: 1
    datasources:
      - name: InfluxDB
        type: influxdb
        access: proxy
        url: http://influxdb-cluster-ip:8086
        database: trigger_hook
        isDefault: true
