apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-message-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: rabbitmq-message
  template:
    metadata:
      labels:
        component: rabbitmq-message
    spec:
      containers:
        - name: rabbitmq-message
          image: rabbitmq-message
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5672
            - containerPort: 15672
            - containerPort: 15671
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: 'rabbitmq'
            - name: RABBITMQ_DEFAULT_PASS
              value: 'secret'
