apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service
spec:
  rules:
    - host: "api.message.com"
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: message-service-nginx-cluster-id
                port:
                  number: 80
    - host: "dashboard.message.com"
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: message-dashboard-cluster-ip
                port:
                  number: 3000
    - host: "rabbitmq.message.com"
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: rabbitmq-message-cluster-ip
                port:
                  number: 15672
    - host: "monitoring.message.com"
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: grafana-cluster-ip
                port:
                  number: 3000
